# Generated by Django 3.1.2 on 2020-10-26 17:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moniker_animal', models.CharField(max_length=100, verbose_name='Кличка')),
                ('createdAt', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('weight_animal', models.IntegerField(max_length=100, verbose_name='Вес')),
                ('height_animal', models.CharField(default='Неизвестно', max_length=100, verbose_name='Рост')),
                ('gender_animal', models.CharField(choices=[(1, 'Мальчик'), (2, 'Девочка')], default='Унисекс', max_length=100, verbose_name='Пол')),
                ('born_on_animal', models.DateField(default=datetime.date.today, verbose_name='Дата рождения')),
                ('type_color_animal', models.CharField(choices=[(1, 'Монотонная'), (2, 'Многоцветная')], max_length=100, verbose_name='Тип окраса')),
                ('color_animal', models.CharField(choices=[(1, 'Черная'), (2, 'Белая'), (3, 'Коричневая'), (4, 'Серая'), (5, 'Рыжая'), (6, 'Полосотая'), (7, 'Пятнистая')], max_length=100, verbose_name='Цвет')),
                ('hair_animal', models.CharField(choices=[(1, 'Пушистая'), (2, 'Короткошерстая'), (3, 'Лысая')], max_length=100, verbose_name='Шерсть')),
                ('sterilization_animal', models.CharField(choices=[(1, 'Да'), (2, 'Нет')], max_length=100, verbose_name='Стерилизован')),
                ('trained_animal', models.CharField(choices=[(1, 'Да'), (2, 'Нет')], max_length=100, verbose_name='Дрессирован\\приучен к лотку')),
                ('vaccinations_animal', models.CharField(default='Не привит', max_length=255, verbose_name='Прививки')),
                ('adress_animal', models.CharField(max_length=255, verbose_name='Адрес приюта')),
            ],
            options={
                'verbose_name': 'Животное',
                'verbose_name_plural': 'Животные',
            },
        ),
    ]
