# Generated by Django 3.1.2 on 2020-10-31 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idcard_registration_animal', models.CharField(default='', max_length=20, verbose_name='карточка учета животного №')),
                ('type_animal', models.CharField(default='', max_length=20, verbose_name='вид')),
                ('age_animal', models.CharField(default='', max_length=20, verbose_name='возраст')),
                ('weight_animal', models.CharField(default='', max_length=20, verbose_name='вес')),
                ('name_animal', models.CharField(default='', max_length=50, verbose_name='кличка')),
                ('gender_animal', models.CharField(default='', max_length=20, verbose_name='пол')),
                ('breed_animal', models.CharField(default='', max_length=20, verbose_name='порода')),
                ('color_animal', models.CharField(default='', max_length=30, verbose_name='окрас')),
                ('hair_animal', models.CharField(default='', max_length=20, verbose_name='шерсть')),
                ('ears_animal', models.CharField(default='', max_length=20, verbose_name='уши')),
                ('tail_animal', models.CharField(default='', max_length=20, verbose_name='хвост')),
                ('size_animal', models.CharField(default='', max_length=20, verbose_name='размер')),
                ('feature_animal', models.CharField(default='', max_length=20, verbose_name='особые приметы')),
                ('avairy_animal', models.CharField(default='', max_length=20, verbose_name='Вольер №')),
                ('identification_mark_animal', models.CharField(default='', max_length=50, verbose_name='идентификационная метка')),
                ('sterilization_date_animal', models.CharField(default='', max_length=50, verbose_name='дата стерилизации')),
                ('veterinarian_name_animal', models.CharField(default='', max_length=200, verbose_name='ф.и.о. ветеринарного врача')),
                ('socialized_animal', models.CharField(default='', max_length=20, verbose_name='Социализировано(да/нет)')),
                ('receipt_report_animal', models.CharField(default='', max_length=20, verbose_name='заказ-наряд / акт о поступлении животного №')),
                ('date_receipt_report_animal', models.CharField(default='', max_length=20, verbose_name='заказ-наряд дата/ акт о поступлении животного, дата')),
                ('administrative_district_animal', models.CharField(default='', max_length=20, verbose_name='административный округ')),
                ('catch_report_animal', models.CharField(default='', max_length=20, verbose_name='акт отлова №')),
                ('catching_address_animal', models.CharField(default='', max_length=250, verbose_name='адрес места отлова')),
                ('legal_entity_animal', models.CharField(default='', max_length=20, verbose_name='юридическое лицо')),
                ('guardians_animal', models.CharField(default='', max_length=200, verbose_name='ф.и.о. опекунов')),
                ('natural_person_animal', models.CharField(default='', max_length=200, verbose_name='физическое лицо ф.и.о.')),
                ('date_admission_toshelter_animal', models.CharField(default='', max_length=20, verbose_name='дата поступления в приют')),
                ('act_animal', models.CharField(default='', max_length=20, verbose_name='акт №')),
                ('date_leaving_shelter_animal', models.CharField(default='', max_length=20, verbose_name='дата выбытия из приюта')),
                ('reason_leaving_animal', models.CharField(default='', max_length=200, verbose_name='причина выбытия')),
                ('contract_leaving_animal', models.CharField(default='', max_length=20, verbose_name='акт/договор №')),
                ('shelter_address_animal', models.CharField(default='', max_length=300, verbose_name='адрес приюта')),
                ('exploit_organization_animal', models.CharField(default='', max_length=50, verbose_name='эксплуатирующая организация')),
                ('head_ofshelter_animal', models.CharField(default='', max_length=50, verbose_name='ф.и.о. руководителя приюта')),
                ('care_worker_animal', models.CharField(default='', max_length=50, verbose_name='ф.и.о. сотрудника по уходу за животным')),
                ('item_no_treatment_animal', models.CharField(default='', max_length=20, verbose_name='№ п/п(сведения об обработке от экто- и эндопаразитов)')),
                ('date_treatment_parasite_animal', models.CharField(default='', max_length=20, verbose_name='дата')),
                ('drug_name_animal', models.CharField(default='', max_length=50, verbose_name='название препарата')),
                ('drug_dosage_animal', models.CharField(default='', max_length=20, verbose_name='доза')),
                ('item_no_vaccine_animal', models.CharField(default='', max_length=20, verbose_name='№ п/п(сведения о вакцинации )')),
                ('date_vaccine_animal', models.CharField(default='', max_length=20, verbose_name='дата')),
                ('type_vaccine_animal', models.CharField(default='', max_length=50, verbose_name='вид вакцины')),
                ('num_serial_animal', models.CharField(default='', max_length=20, verbose_name='№ серии')),
                ('date_inspection_animal', models.CharField(default='', max_length=20, verbose_name='дата осмотра')),
                ('anamnesis_animal', models.CharField(default='', max_length=30, verbose_name='анамнез')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animals',
            },
        ),
    ]
