# Generated by Django 3.1.2 on 2020-10-31 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='legal_entity_animal',
            field=models.CharField(default='FFF', max_length=20, null=True, verbose_name='юридическое лицо'),
        ),
    ]
