# Generated by Django 3.1.2 on 2020-10-31 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='main_images',
            field=models.ImageField(blank=True, null=True, upload_to='./images'),
        ),
    ]
