# Generated by Django 3.1.2 on 2020-10-26 18:14

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='color_animal',
            field=models.IntegerField(choices=[(1, 'Монотонная'), (2, 'Многоцветная'), (1, 'Черная'), (2, 'Белая'), (3, 'Коричневая'), (4, 'Серая'), (5, 'Рыжая'), (6, 'Полосатая'), (7, 'Пятнистая'), (8, 'Монотонная'), (9, 'Многоцветная')], verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='gender_animal',
            field=models.CharField(choices=[('boy', 'Мальчик'), ('girl', 'Девочка')], default='Унисекс', max_length=100, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='hair_animal',
            field=models.IntegerField(choices=[(1, 'Пушистая'), (2, 'Короткошерстая'), (3, 'Лысая')], verbose_name='Шерсть'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='height_animal',
            field=models.IntegerField(default='', verbose_name='Рост'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='sterilization_animal',
            field=models.IntegerField(choices=[(1, 'Да'), (2, 'Нет')], verbose_name='Стерилизован'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='trained_animal',
            field=models.IntegerField(choices=[(1, 'Да'), (2, 'Нет')], verbose_name='Дрессирован\\приучен к лотку'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='type_color_animal',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Монотонная'), (2, 'Многоцветная')], max_length=3, verbose_name='Тип окраса'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='weight_animal',
            field=models.IntegerField(verbose_name='Вес'),
        ),
    ]
