# Generated by Django 3.1.2 on 2020-10-30 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Backend', '0002_auto_20201026_2114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'verbose_name': 'Animal', 'verbose_name_plural': 'Animals'},
        ),
        migrations.AddField(
            model_name='animal',
            name='user_animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='color_animal',
            field=models.CharField(choices=[('black', 'Черная'), ('white', 'Белая'), ('brown', 'Коричневая'), ('grey', 'Серая'), ('redhead', 'Рыжая'), ('striped', 'Полосатая'), ('spotted', 'Пятнистая')], max_length=100, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='hair_animal',
            field=models.CharField(choices=[('longhaired', 'Пушистая'), ('shorthaired', 'Короткошерстая'), ('hairless', 'Безволосая')], max_length=100, verbose_name='Шерсть'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='sterilization_animal',
            field=models.CharField(choices=[('yes', 'Да'), ('no', 'Нет')], max_length=100, verbose_name='Стерилизован'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='trained_animal',
            field=models.CharField(choices=[('yes', 'Да'), ('no', 'Нет')], max_length=100, verbose_name='Дрессирован\\приучен к лотку'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='type_color_animal',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('monochrome', 'Монотонная'), ('multicolor', 'Многоцветная')], max_length=10, verbose_name='Тип окраса'),
        ),
    ]
