# Generated by Django 3.1.2 on 2020-10-31 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0002_auto_20201031_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='guardians_animal',
            field=models.CharField(default='', max_length=200, null=True, verbose_name='ф.и.о. опекунов'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='natural_person_animal',
            field=models.CharField(default='', max_length=200, null=True, verbose_name='физическое лицо ф.и.о.'),
        ),
    ]
