# Generated by Django 3.1.2 on 2020-10-31 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0002_animal_main_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='act_animal',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='акт №'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='administrative_district_animal',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='административный округ'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='age_animal',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='возраст'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='anamnesis_animal',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='анамнез'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='avairy_animal',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Вольер №'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='breed_animal',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='порода'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='care_worker_animal',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='ф.и.о. сотрудника по уходу за животным'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='catch_report_animal',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='акт отлова №'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='catching_address_animal',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='адрес места отлова'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='color_animal',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='окрас'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='contract_leaving_animal',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='акт/договор №'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='date_admission_toshelter_animal',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='дата поступления в приют'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='date_inspection_animal',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='дата осмотра'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='date_leaving_shelter_animal',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='дата выбытия из приюта'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='date_receipt_report_animal',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='заказ-наряд дата/ акт о поступлении животного, дата'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='date_treatment_parasite_animal',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='дата'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='date_vaccine_animal',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='дата'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='drug_dosage_animal',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='доза'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='drug_name_animal',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='название препарата'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='ears_animal',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='уши'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='exploit_organization_animal',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='эксплуатирующая организация'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='feature_animal',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='особые приметы'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='gender_animal',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='пол'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='guardians_animal',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='ф.и.о. опекунов'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='hair_animal',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='шерсть'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='head_ofshelter_animal',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='ф.и.о. руководителя приюта'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='identification_mark_animal',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='идентификационная метка'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='item_no_treatment_animal',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='№ п/п(сведения об обработке от экто- и эндопаразитов)'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='item_no_vaccine_animal',
            field=models.CharField(blank=True, default='', max_length=2000, null=True, verbose_name='№ п/п(сведения о вакцинации )'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='legal_entity_animal',
            field=models.CharField(blank=True, default='FFF', max_length=100, null=True, verbose_name='юридическое лицо'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='name_animal',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='кличка'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='natural_person_animal',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='физическое лицо ф.и.о.'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='num_serial_animal',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='№ серии'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='reason_leaving_animal',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='причина выбытия'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='receipt_report_animal',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='заказ-наряд / акт о поступлении животного №'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='shelter_address_animal',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='адрес приюта'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='size_animal',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='размер'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='socialized_animal',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Социализировано(да/нет)'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='sterilization_date_animal',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='дата стерилизации'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='tail_animal',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='хвост'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='type_animal',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='вид'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='type_vaccine_animal',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='вид вакцины'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='veterinarian_name_animal',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='ф.и.о. ветеринарного врача'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='weight_animal',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='вес'),
        ),
        migrations.CreateModel(
            name='TaskImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, upload_to='')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.animal')),
            ],
        ),
    ]
