# Generated by Django 3.1.2 on 2020-10-31 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0003_auto_20201031_1848'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskImage',
        ),
    ]
