# Generated by Django 3.1.2 on 2020-10-31 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0005_auto_20201031_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='age_animal',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='возраст'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='avairy_animal',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Вольер №'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='breed_animal',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='порода'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='catching_address_animal',
            field=models.CharField(default='', max_length=250, null=True, verbose_name='адрес места отлова'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='color_animal',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='окрас'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='ears_animal',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='уши'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='feature_animal',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='особые приметы'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='gender_animal',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='пол'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='hair_animal',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='шерсть'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='idcard_registration_animal',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='карточка учета животного №'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='identification_mark_animal',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='идентификационная метка'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='name_animal',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='кличка'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='size_animal',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='размер'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='sterilization_date_animal',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='дата стерилизации'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='tail_animal',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='хвост'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='type_animal',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='вид'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='weight_animal',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='вес'),
        ),
    ]
